server:
  port: 8190
  servlet:
    context-path: /market
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:mydatabase;MODE=PostgreSQL
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2

  jpa:
    show-sql: true
    properties:
      hibernate:
      dialect: org.hibernate.dialect.H2Dialect


#      settings:
#        web-allow-others: false
